const CURRENT_URL='https://raw.githubusercontent.com/EngTW/English-for-Programmers/main/lists/Taiwan-high-school-6K-108-edition/Data/Taiwan-high-school-english-reference-vocabulary-list-108-edition.json';
const LEGACY_URL='https://raw.githubusercontent.com/mahavivo/english-wordlists/master/%E5%8F%B0%E7%81%A3%E9%AB%98%E4%B8%AD%E8%8B%B1%E6%96%87%E5%8F%83%E8%80%83%E8%A9%9E%E5%BD%99%E8%A1%A8.txt';
const STORAGE_KEY='hs7000-v1';
const FALLBACK=[
 {word:'ability',pos:['n.'],level:1,meaning:'能力；才能'},{word:'accept',pos:['v.'],level:2,meaning:'接受'},{word:'achieve',pos:['v.'],level:3,meaning:'達成；實現'},{word:'academic',pos:['adj.'],level:4,meaning:'學術的'},{word:'acknowledge',pos:['v.'],level:5,meaning:'承認；確認'},{word:'abbreviate',pos:['v.'],level:6,meaning:'縮寫'},{word:'abandon',pos:['v.'],level:4,meaning:'放棄；遺棄'},{word:'abrupt',pos:['adj.'],level:5,meaning:'突然的'},{word:'abundance',pos:['n.'],level:6,meaning:'豐富；充裕'},{word:'accurate',pos:['adj.'],level:3,meaning:'準確的'},{word:'adjust',pos:['v.'],level:4,meaning:'調整'},{word:'admit',pos:['v.'],level:2,meaning:'承認；允許進入'},{word:'adventure',pos:['n.'],level:3,meaning:'冒險'},{word:'affect',pos:['v.'],level:2,meaning:'影響'},{word:'agriculture',pos:['n.'],level:3,meaning:'農業'},{word:'aisle',pos:['n.'],level:5,meaning:'走道'},{word:'allocate',pos:['v.'],level:5,meaning:'分配'},{word:'ambiguous',pos:['adj.'],level:6,meaning:'模稜兩可的'},{word:'analyze',pos:['v.'],level:4,meaning:'分析'},{word:'annual',pos:['adj.'],level:4,meaning:'每年的'}
];
let bank=[], session=[], sessionIndex=0, quiz=[], quizIndex=0, quizScore=0;
let state=loadState();

function loadState(){try{return Object.assign({progress:{},mistakes:{},stats:{correct:0,total:0},settings:{dailyGoal:20,mode:'7000',autoSpeak:true},lastStudy:null,streak:0},JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}'))}catch{return {progress:{},mistakes:{},stats:{correct:0,total:0},settings:{dailyGoal:20,mode:'7000',autoSpeak:true},lastStudy:null,streak:0}}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function normalizeWord(w){return w.toLowerCase().replace(/^\*/,'').trim()}
function parseLegacy(text){const map=new Map();text.split(/\r?\n/).forEach(line=>{line=line.trim();if(!line||/^[A-Z]$/.test(line)||line.includes('大學學測'))return;const m=line.match(/^\*?([A-Za-z][A-Za-z.'-]*(?:\s+[A-Za-z][A-Za-z.'-]*)?)\s+(.+)$/);if(!m)return;const word=normalizeWord(m[1]);let rest=m[2].trim();const posMatch=rest.match(/^((?:adj\.|adv\.|n\.|v\.|prep\.|conj\.|pron\.|art\.|num\.|aux\.|int\.)[^\u4e00-\u9fff]*)/i);let pos=[],meaning=rest;if(posMatch){pos=posMatch[1].split(/[\/;, ]+/).filter(x=>x.includes('.'));meaning=rest.slice(posMatch[0].length).trim()}map.set(word,{meaning:meaning||'—',pos})});return map}
function exampleFor(word){const templates={ability:'She has the ability to solve difficult problems.',accept:'I accept your idea and will think about it.',achieve:'Small daily steps can help you achieve your goal.',academic:'Good reading habits support academic success.',abandon:'They had to abandon the plan because of the weather.',accurate:'Please make sure the information is accurate.',adjust:'It takes time to adjust to a new school.',analyze:'We need to analyze the data before deciding.'};return templates[word]||`Try to use “${word}” in a sentence of your own.`}
async function loadBank(){document.getElementById('bankStatus').textContent='載入字庫…';try{const [curRes,oldRes]=await Promise.all([fetch(CURRENT_URL),fetch(LEGACY_URL)]);if(!curRes.ok||!oldRes.ok)throw new Error('network');const current=await curRes.json();const legacy=parseLegacy(await oldRes.text());const currentSet=new Set();bank=current.map(x=>{const word=normalizeWord(x.Word);currentSet.add(word);const old=legacy.get(word);return {word,pos:x.PartsOfSpeech||old?.pos||[],level:Number(x.Level)||1,meaning:old?.meaning||'中文釋義待補充',source:'108'}});const extras=[];for(const [word,info] of legacy){if(!currentSet.has(word)&&extras.length<1000)extras.push({word,pos:info.pos,level:7,meaning:info.meaning,source:'legacy'})}bank.push(...extras);document.getElementById('bankStatus').textContent=`已載入 ${bank.length.toLocaleString()} 字`;}
 catch(e){bank=[...FALLBACK];document.getElementById('bankStatus').textContent='離線示範字庫';}
 renderAll();}
function eligibleBank(){const mode=state.settings.mode;return bank.filter(w=>mode==='7000'?true:mode==='6000'?w.level<=6:w.level<=4)}
function getProgress(word){return state.progress[word]||null}
function isDue(p){return p&&p.due&&new Date(p.due)<=new Date()}
function getNewWords(n){return eligibleBank().filter(w=>!getProgress(w.word)).slice(0,n)}
function getDueWords(){return eligibleBank().filter(w=>isDue(getProgress(w.word))).sort((a,b)=>new Date(getProgress(a.word).due)-new Date(getProgress(b.word).due))}
function updateStreak(){const today=new Date().toISOString().slice(0,10);if(state.lastStudy===today)return;const y=new Date(Date.now()-86400000).toISOString().slice(0,10);state.streak=state.lastStudy===y?(state.streak||0)+1:1;state.lastStudy=today;saveState()}
function speak(word){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(word);u.lang='en-US';u.rate=.9;speechSynthesis.speak(u)}
function renderAll(){renderHome();renderLevels();renderBook();renderProgress();syncSettingsUI()}
function renderHome(){const total=eligibleBank().length,learned=eligibleBank().filter(w=>getProgress(w.word)).length,due=getDueWords().length;const today=Math.min(Number(state.settings.dailyGoal)||20,getNewWords(999).length);document.getElementById('learnedCount').textContent=learned;document.getElementById('reviewCount').textContent=due;document.getElementById('streakCount').textContent=state.streak||0;document.getElementById('accuracyCount').textContent=state.stats.total?Math.round(state.stats.correct/state.stats.total*100)+'%':'—';document.getElementById('todaySummary').textContent=due?`${due} 字到期複習，再學 ${today} 個新字`:`今天安排 ${today} 個新字`;const pct=total?Math.round(learned/total*100):0;document.getElementById('todayPct').textContent=pct+'%';document.getElementById('todayRing').style.setProperty('--p',pct+'%')}
function renderLevels(){const el=document.getElementById('levelList');el.innerHTML='';const labels=['','基礎地基','高一核心','中級過渡','學測主力','高分衝刺','進階查閱','7000 補充'];for(let lv=1;lv<=7;lv++){if(lv===7&&state.settings.mode!=='7000')continue;const words=eligibleBank().filter(w=>w.level===lv),learned=words.filter(w=>getProgress(w.word)).length;const d=document.createElement('div');d.className='level-card';d.innerHTML=`<div class="level-badge">L${lv}</div><div><h4>${lv===7?'進階補充':`Level ${lv}`} · ${labels[lv]}</h4><p>${learned.toLocaleString()} / ${words.length.toLocaleString()} 已學</p></div><strong>${words.length?Math.round(learned/words.length*100):0}%</strong>`;d.onclick=()=>startSession(words.filter(w=>!getProgress(w.word)).slice(0,state.settings.dailyGoal));el.appendChild(d)}}
function startSession(words){session=words.length?words:getDueWords().slice(0,state.settings.dailyGoal);if(!session.length){alert('目前沒有需要學習的單字。');return}sessionIndex=0;showView('learn');showSessionWord()}
function showSessionWord(){const w=session[sessionIndex];if(!w){renderAll();showView('home');return}document.getElementById('wordText').textContent=w.word;document.getElementById('wordLevel').textContent=w.level===7?'進階補充':`Level ${w.level}`;document.getElementById('wordPos').textContent=(w.pos||[]).join(' / ')||'—';document.getElementById('wordMeaning').textContent=w.meaning;document.getElementById('wordExample').textContent=exampleFor(w.word);document.getElementById('wordHint').textContent=w.meaning==='中文釋義待補充'?'此字為新版新增/舊字表未對應，V1.1 將補完整中文釋義。':'';document.getElementById('answerArea').classList.add('hidden');document.getElementById('ratingGrid').classList.add('hidden');document.getElementById('showAnswerBtn').classList.remove('hidden');document.getElementById('sessionCounter').textContent=`${sessionIndex+1}/${session.length}`;document.getElementById('sessionProgress').style.width=`${sessionIndex/session.length*100}%`;if(state.settings.autoSpeak)speak(w.word)}
function gradeWord(grade){const w=session[sessionIndex],old=getProgress(w.word)||{interval:0,ease:2.3,reps:0};let days=0;if(grade==='again'){days=0;old.interval=0;old.reps=0}else if(grade==='hard'){days=1;old.interval=1;old.reps++}else if(grade==='good'){days=old.interval?Math.max(3,Math.round(old.interval*2.2)):3;old.interval=days;old.reps++}else{days=old.interval?Math.max(7,Math.round(old.interval*3)):7;old.interval=days;old.reps++}const due=new Date(Date.now()+days*86400000+(grade==='again'?10*60000:0));state.progress[w.word]={...old,last:new Date().toISOString(),due:due.toISOString(),grade};updateStreak();saveState();sessionIndex++;showSessionWord()}
function renderBook(){const q=(document.getElementById('searchInput')?.value||'').toLowerCase(),lv=document.getElementById('bookLevel')?.value||'all';let items=eligibleBank().filter(w=>(lv==='all'||String(w.level)===lv)&&(!q||w.word.includes(q)||w.meaning.includes(q))).slice(0,250);document.getElementById('bookCount').textContent=`${items.length}${items.length===250?'+' :''} 字`;const el=document.getElementById('wordList');el.innerHTML='';items.forEach(w=>{const d=document.createElement('div');d.className='word-row';d.innerHTML=`<div><b>${w.word}</b><small>${(w.pos||[]).join(' / ')}</small><p>${w.meaning}</p></div><span class="tag">${w.level===7?'ADV':`L${w.level}`}</span>`;d.onclick=()=>speak(w.word);el.appendChild(d)})}
function renderProgress(){const eligible=eligibleBank(),learned=eligible.filter(w=>getProgress(w.word)).length;document.getElementById('overallLearned').textContent=learned;document.getElementById('overallTotal').textContent=eligible.length;document.getElementById('overallBar').style.width=(eligible.length?learned/eligible.length*100:0)+'%';const el=document.getElementById('levelProgress');el.innerHTML='';for(let lv=1;lv<=7;lv++){const arr=eligible.filter(w=>w.level===lv);if(!arr.length)continue;const n=arr.filter(w=>getProgress(w.word)).length;const d=document.createElement('div');d.className='progress-row';d.innerHTML=`<b>${lv===7?'進階':`L${lv}`}</b><div class="mini-track"><div style="width:${n/arr.length*100}%"></div></div><span>${n}/${arr.length}</span>`;el.appendChild(d)}const mistakes=Object.keys(state.mistakes).length;document.getElementById('mistakeSummary').textContent=mistakes?`目前有 ${mistakes} 個單字需要加強。`:'目前沒有錯題。'}
function makeQuizPool(){const scope=document.getElementById('quizScope').value;let pool=eligibleBank();if(scope==='learned')pool=pool.filter(w=>getProgress(w.word));else if(scope==='mistakes')pool=pool.filter(w=>state.mistakes[w.word]);else if(/^[1-7]$/.test(scope))pool=pool.filter(w=>String(w.level)===scope);return pool.filter(w=>w.meaning&&w.meaning!=='中文釋義待補充')}
function beginQuiz(){const pool=makeQuizPool(),count=Math.min(Number(document.getElementById('quizCount').value),pool.length);if(count<4){alert('目前可測驗的單字不足 4 個，請先學一些單字或切換範圍。');return}quiz=[...pool].sort(()=>Math.random()-.5).slice(0,count);quizIndex=0;quizScore=0;document.getElementById('quizSetup').classList.add('hidden');document.getElementById('quizArea').classList.remove('hidden');showQuiz()}
function showQuiz(){if(quizIndex>=quiz.length){const pct=Math.round(quizScore/quiz.length*100);document.getElementById('quizArea').innerHTML=`<div class="dashboard-card"><h2>測驗完成</h2><div class="big-number">${pct}%</div><p>答對 ${quizScore} / ${quiz.length} 題</p><button class="primary big" onclick="location.reload()">完成</button></div>`;renderAll();return}const w=quiz[quizIndex],pool=eligibleBank().filter(x=>x.meaning&&x.meaning!=='中文釋義待補充'&&x.word!==w.word);const distract=[...pool].sort(()=>Math.random()-.5).slice(0,3);const opts=[w,...distract].sort(()=>Math.random()-.5);document.getElementById('quizIndex').textContent=`${quizIndex+1}/${quiz.length}`;document.getElementById('quizScore').textContent=`${quizScore} 分`;document.getElementById('quizWord').textContent=w.word;document.getElementById('quizFeedback').textContent='';document.getElementById('nextQuizBtn').classList.add('hidden');const el=document.getElementById('quizOptions');el.innerHTML='';opts.forEach(o=>{const b=document.createElement('button');b.className='option';b.textContent=o.meaning;b.onclick=()=>answerQuiz(b,o.word===w.word,w);el.appendChild(b)})}
function answerQuiz(btn,correct,w){document.querySelectorAll('.option').forEach(b=>b.disabled=true);state.stats.total++;if(correct){btn.classList.add('correct');quizScore++;state.stats.correct++;document.getElementById('quizFeedback').textContent='答對了！'}else{btn.classList.add('wrong');state.mistakes[w.word]=(state.mistakes[w.word]||0)+1;document.getElementById('quizFeedback').textContent=`正確：${w.meaning}`;document.querySelectorAll('.option').forEach(b=>{if(b.textContent===w.meaning)b.classList.add('correct')})}saveState();document.getElementById('nextQuizBtn').classList.remove('hidden')}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.target===name));if(name==='book')renderBook();if(name==='progress')renderProgress();window.scrollTo({top:0,behavior:'smooth'})}
function syncSettingsUI(){document.getElementById('dailyGoal').value=state.settings.dailyGoal||20;document.getElementById('studyMode').value=state.settings.mode||'7000';document.getElementById('autoSpeak').checked=state.settings.autoSpeak!==false}
function bind(){document.querySelectorAll('.nav-item').forEach(n=>n.onclick=()=>showView(n.dataset.target));document.getElementById('startTodayBtn').onclick=()=>startSession([...getDueWords(),...getNewWords(Number(state.settings.dailyGoal)||20)].slice(0,Number(state.settings.dailyGoal)||20));document.getElementById('startReviewBtn').onclick=()=>startSession(getDueWords());document.getElementById('exitLearnBtn').onclick=()=>showView('home');document.getElementById('showAnswerBtn').onclick=()=>{document.getElementById('answerArea').classList.remove('hidden');document.getElementById('ratingGrid').classList.remove('hidden');document.getElementById('showAnswerBtn').classList.add('hidden')};document.querySelectorAll('.rate').forEach(b=>b.onclick=()=>gradeWord(b.dataset.grade));document.getElementById('speakBtn').onclick=()=>session[sessionIndex]&&speak(session[sessionIndex].word);document.getElementById('beginQuizBtn').onclick=beginQuiz;document.getElementById('nextQuizBtn').onclick=()=>{quizIndex++;showQuiz()};document.getElementById('quizSpeakBtn').onclick=()=>quiz[quizIndex]&&speak(quiz[quizIndex].word);document.getElementById('searchInput').oninput=renderBook;document.getElementById('bookLevel').onchange=renderBook;document.getElementById('settingsBtn').onclick=()=>document.getElementById('settingsDialog').showModal();document.getElementById('saveSettingsBtn').onclick=()=>{state.settings.dailyGoal=Math.max(5,Math.min(100,Number(document.getElementById('dailyGoal').value)||20));state.settings.mode=document.getElementById('studyMode').value;state.settings.autoSpeak=document.getElementById('autoSpeak').checked;saveState();renderAll()};document.getElementById('practiceMistakesBtn').onclick=()=>{document.getElementById('quizScope').value='mistakes';showView('quiz')};document.getElementById('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='高中英文7000字-學習紀錄.json';a.click();URL.revokeObjectURL(a.href)};document.getElementById('importInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{state=Object.assign(state,JSON.parse(await f.text()));saveState();renderAll();alert('匯入完成')}catch{alert('檔案格式不正確')}};document.getElementById('resetBtn').onclick=()=>{if(confirm('確定清除所有學習進度？')){localStorage.removeItem(STORAGE_KEY);location.reload()}}}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
bind();loadBank();
